---
- name: "Apply netplan"
  become: True
  become_user: root
  shell: "netplan apply"
  when:
    - netplan_step.changed

- name: "Test for domain membership"
  become: True
  become_user: root
  shell: wbinfo -t
  register: membership_check
  changed_when: false
  ignore_errors: True

- name: Destroy existing Kerberos Credentials
  become: True
  become_user: root
  command: kdestroy -A
  when:
    - (((unjoin|bool) and (membership_check is successful)) or ((not unjoin|bool) and (membership_check is failed)))

- name: Generate a Kerberos Key
  become: True
  become_user: root
  shell: |
    echo -n '{{ admin_password }}' | kinit '{{ admin_user }}'
  no_log: True
  when:
    - (((unjoin|bool) and (membership_check is successful)) or ((not unjoin|bool) and (membership_check is failed)))

- name: Join the Active Directory
  become: True
  become_user: root
  command: net ads join -k
  when:
    - not unjoin|bool
    - membership_check is failed
  notify:
    - restart smbd
    - restart nmbd
    - restart winbind
    - restart ssh

- name: Update hostname locally
  hostname:
    name: "{{ hostname }}"
  when:
    - not unjoin|bool

- name: Leave the Active Directory
  become: True
  become_user: root
  command: net ads leave -k
  when:
    - unjoin|bool
    - membership_check is successful

- name: Remove extra netplan rules on unjoin
  file:
    path: "/etc/netplan/500-{{ netbios }}-netplan.yaml"
    state: absent
  when:
    - unjoin|bool
