---
- name: install python3 and pip
  apt:
    name: python3,python3-pip
    state: present

- name: pip install ansible and virtualenv
  pip:
    name:
      - ansible==2.7.9
      - virtualenv
    state: present
