---
- name: Apt upgrade, then install all required packages
  import_tasks: pkg-install.yml
  when: pkg_update|bool

- name: Adjust Ansible installation on server
  import_tasks: ansible-install.yml
  when: ansible_install|bool

- name: Fill out the /etc/hosts file
  import_tasks: etc-hosts.yml

- name: Configure NTP
  import_tasks: ntp.yml

- name: Configure Netplan
  import_tasks: netplan.yml

- name: Configure Kerberos5
  import_tasks: krb5.yml

- name: Configure Samba
  import_tasks: samba.yml

- name: Add winbind to nsswitch
  import_tasks: nsswitch.yml

- name: Active Directory tasks
  import_tasks: active-directory.yml

- name: Update authentication methods
  import_tasks: authentication.yml
