---
- name: "Test the network"
  become: True
  become_user: root
  shell: "nslookup {{ ldap_domain }}"
  register: domain_check
  ignore_errors: True

- name: "Apply netplan"
  become: True
  become_user: root
  shell: "netplan apply"
  when:
    - domain_check is failed

- name: "Test for domain membership"
  become: True
  become_user: root
  shell: wbinfo -t
  register: membership_check
  ignore_errors: True

- name: Destroy existing Kerberos Credentials
  become: True
  become_user: root
  command: kdestroy -A

- name: Generate a Kerberos Key
  become: True
  become_user: root
  shell: |
    echo -n '{{ admin_password }}' | kinit '{{ admin_user }}'
  no_log: True

- name: Join the Active Directory
  become: True
  become_user: root
  command: net ads join -k
  when:
    - unjoin is not defined
    - membership_check is failed
  notify:
    - restart smbd
    - restart nmbd
    - restart winbind
    - restart ssh

- name: Leave the Active Directory
  become: True
  become_user: root
  command: net ads leave -k
  when:
    - unjoin is defined
    - membership_check is successful
