---
# PAM configurations
- name: Enable home Directories
  become: True
  become_user: root
  lineinfile:
    dest: /etc/pam.d/common-session
    regexp: '^session*.*homedir*.*$'
    line: 'session optional                        pam_mkhomedir.so'
    state: present
    insertbefore: "# end of pam-auth-update config"

### Consider replacing this with "blockinfile" - it's overkill
# Disallow non-root logins when /etc/nologin exists.
# account    required     pam_nologin.so
# account sufficient pam_succeed_if.so user ingroup sudo
# {% if ssh_access_groups is defined %}
# {% for access_group in ssh_access_groups %}
# account sufficient pam_succeed_if.so user ingroup [{{ netbios }}\{{ access_group }}]
# {% endfor %}
# {% endif %}

- name: Append SSH Login Groups
  become: True
  become_user: root
  template:
    src: pam.d_sshd.j2
    dest: /etc/pam.d/sshd
    owner: root
    mode: 0644

- name: Disable SSH common-account
  become: True
  become_user: root
  lineinfile:
    dest: /etc/pam.d/sshd
    regexp: '^@include common-account$'
    line: '# @include common-account'
    state: present


- name: Enable SSH common-account
  become: True
  become_user: root
  lineinfile:
    dest: /etc/pam.d/sshd
    regexp: '^#.*@include common-account$'
    line: '@include common-account'
    state: present
  when:
    - unjoin

# SSH Configurations
- name: Add SSH banner
  become: True
  become_user: root
  template:
    src: ssh-banner.j2
    dest: /etc/ssh/ehe-ssh-banner
    owner: root
    mode: 0644

- name: Enable SSH PasswordAuthentication
  become: True
  become_user: root
  lineinfile:
    dest: /etc/ssh/sshd_config
    backup: True
    regexp: 'PasswordAuthentication no'
    line: '# PasswordAuthentication no'
    state: present
  notify:
    - restart ssh
  when:
    - not unjoin

- name: Disable SSH PasswordAuthentication
  become: True
  become_user: root
  lineinfile:
    dest: /etc/ssh/sshd_config
    backup: True
    regexp: '# PasswordAuthentication no'
    line: 'PasswordAuthentication no'
    state: present
  when:
    - unjoin
  notify:
    - restart ssh

- set_fact:
    ssh_access_group: "{{ ssh_access_groups | default('[]') }}"
    sudo_access: "{{ sudo_access | default('[]') }}"

- name: Enforce SSH security requirements
  become: True
  become_user: root
  blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      ClientAliveInterval 300
      ClientAliveCountMax 0
      LogLevel INFO
      AllowTcpForwarding     no
      PermitTunnel           no
      PermitUserEnvironment  no
      Banner /etc/ssh/ehe-ssh-banner
      Match Group "{{ ((ssh_access_groups + sudo_access) | unique) | join(',') }}"
        PasswordAuthentication yes
        PubkeyAuthentication no
    insertafter: EOF
    state: present
  when:
    - not unjoin
  # notify:
  #   - restart ssh

- name: Remove SSH Key Restriction
  become: True
  become_user: root
  blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      Match Group "{{ ((ssh_access_groups + sudo_access) | unique) | join(',') }}"
        PasswordAuthentication yes
        PubkeyAuthentication no
    state: absent
  when:
    - unjoin

- name: Reset Local SSH
  shell: sleep 1; pkill -u {{ ansible_ssh_user }} sshd
  async: 3
  poll: 2
  when: ssh_reset

# SUDOERS configurations

- name: Add access groups to sudoers.d
  become: True
  become_user: root
  template:
    src: sudoers.d.j2
    dest: "/etc/sudoers.d/100-{{ netbios }}-sudoers"
    owner: root
    mode: 0440
    validate: 'visudo -cf %s'

- name: Remove access from "{{ netbios }}" sudoers groups
  file:
    path: "/etc/sudoers.d/100-{{ netbios }}-sudoers"
    state: absent
  when: unjoin



# - name: "Restore sudo access to original state"
#   become: True
#   become_user: root
#   lineinfile:
#     dest: /etc/sudoers
#     line: '"%{{ item }}" ALL=(ALL) ALL'
#     insertafter: '# Members of the admin group may gain root privileges'
#     backup: yes
#     state: absent
#   with_items:
#     - "{{ sudo_access }}"
#   when:
#     - unjoin
#
# - name: "Remove Sudo Access as well as surrounding markers"
#   become: True
#   become_user: root
#   blockinfile:
#     path: /etc/sudoers
#     marker: "<!-- {mark} MANAGED BY ANSILE ROLE: LINUX AD CONFIGURATION -->"
#     content: ""
#   when:
#     - unjoin

# - name: "Grant access to sudo groups"
#   become: True
#   become_user: root
#   lineinfile:
#     dest: /etc/sudoers
#     line: '"%{{ item }}" ALL=(ALL) ALL'
#     insertafter: '# Members of the admin group may gain root privileges'
#     backup: yes
#     state: present
#   with_items:
#     - "{{ sudo_access }}"
#   when:
#     - not unjoin
#
# - name: "Grant access to sudo groups"
#   become: True
#   become_user: root
#   blockinfile:
#     path: /etc/sudoers
#     block: |
#       "{{ item }}"
#     marker: "<!-- {mark} MANAGED BY ANSILE ROLE: LINUX AD CONFIGURATION -->"
#     insertafter: "# Members of the admin group may gain root privileges"
#   with_items:
#     - "%{{ sudo_access }} ALL=(ALL) ALL"
#   when:
#     - not unjoin
