---
- name: Append servers to /etc/hosts
  become: True
  become_user: root
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ item.ip }}.*$"
    line: "{{ item.ip }}\t\t{{ item.names | join(' ') }}"
    insertafter: '^127*.*1.*localhost'
    state: present
  with_items:
  - ip: "{{ ansible_default_ipv4.address }}"
    names:
      - "{{ hostname }}.{{ ldap_domain }}"
      - "{{ hostname }}"
      - "{{ hostname|upper }}.{{ ldap_domain|upper }}"
      - "{{ hostname|upper }}"
  - ip: "{{ pdc2_server_ip }}"
    names:
      - "{{ pdc2_host }}.{{ pdc2_domain }}"
      - "{{ pdc2_host }}"
      - "{{ pdc2_host|upper }}.{{ pdc2_domain|upper }}"
      - "{{ pdc2_host|upper }}"
  - ip: "{{ pdc2_server_ip }}"
    names:
      - "{{ pdc2_host }}.{{ pdc2_domain }}"
      - "{{ pdc2_host }}"
      - "{{ pdc2_host|upper }}.{{ pdc2_domain|upper }}"
      - "{{ pdc2_host|upper }}"
  - ip: "{{ ldap_server_ip }}"
    names:
      - "{{ ldap_host }}.{{ ldap_domain }}"
      - "{{ ldap_host }}"
      - "{{ ldap_host|upper }}.{{ ldap_domain|upper }}"
      - "{{ ldap_host|upper }}"
