---
- name: "Gather vSRX Facts for all tasks"
  import_tasks: vsrx_facts.yml
  delegate_to: localhost

- name: "Gather AWS Facts for AWS tasks"
  import_tasks: aws_facts.yml
  delegate_to: localhost

- name: "Setup Spoke Virtual Gateway and Customer Gateway"
  import_tasks: spoke_setup.yml
  delegate_to: localhost

- name: "Setup vSRX Device for Usage"
  import_tasks: vsrx_setup.yml
  delegate_to: localhost

- name: "Setup Tunnel Facts"
  import_tasks: setup_tunnel_facts.yml
  delegate_to: localhost

- name: "Setup EHE Tunnel"
  import_tasks: ehe_tunnel.yml
  delegate_to: localhost

- name: "Setup Spoke VPCs"
  import_tasks: aws_spoke.yml
  delegate_to: localhost
