---
- name: "Add Netplan rules at /etc/netplan/500-{{ netbios }}-netplan.yaml"
  become: yes
  become_user: root
  copy:
    dest: "/etc/netplan/500-{{ netbios }}-netplan.yaml"
    content: |
      ---
      network:
          version: 2
          ethernets:
             {{ netplan_interface }}:
                  dhcp4: true
                  match:
                      macaddress: {{ netplan_mac }}
                  set-name: {{ netplan_interface }}
                  nameservers:
                    search: [ {% if pdc is defined %}{{ (netplan_ec2 + pdc) | map(attribute='domain') | unique | join(', ') }}{% endif %} ]
                    addresses: [ {% if pdc is defined %}{{ (netplan_ec2 + pdc) | map(attribute='server_ip') | unique | join(', ') }}{% endif %} ]
    mode: 0644
  notify: restart netplan

- name: Create a cron job that continuously applies netplan
  become: True
  become_user: root
  cron:
    name: "enforce netplan"
    minute: "*/5"
    job: "netplan apply >/dev/null 2>&1"
