---
- name: Add winbind to nsswitch
  lineinfile:
    dest=/etc/nsswitch.conf
    backup=True
    backrefs=True
    state=present
    regexp='^(passwd.*(?<!winbind))$'
    line='\1 winbind'
  lineinfile:
    dest=/etc/nsswitch.conf
    backup=True
    backrefs=True
    state=present
    regexp='^(group.*(?<!winbind))$'
    line='\1 winbind'
