---
- name: Add winbind to nsswitch
  become: True
  become_user: root
  replace:
    path: /etc/nsswitch.conf
    regexp: '^(passwd.*(?<!winbind))$\n^(group.*(?<!winbind))$'
    replace: '\1 winbind\n\2 winbind'
    backup: yes
