--- # OUTLINE OF ACTIVE DIRECTORY LINUX INTEGRATION
- hosts: ehe-bastion
  remote_user: ubuntu
  sudo: yes
- tasks:
  apt: update -y
  apt: upgrade -y
  # command: sudo apt update -y && sudo DEBIAN_FRONTEND=noninteractive apt -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" dist-upgrade
  # Grub menu.1st: keep version currently installed
  # init: 6 ---> wait until the end....?
----
# Don't assume the inventory_hostname is resolvable and delay 10 seconds at start
- name: Wait 300 seconds for port 22 to become open and contain "OpenSSH"
  wait_for:
    port: 22
    host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
    search_regex: OpenSSH
    delay: 10
  connection: local
----
  cmd:
  # wait for reboot
  apt: install -y
    package: ntp ntpdate winbind samba libnss-winbind libpam-winbind krb5-config krb5-locales krb5-user
    # or if this an sssd install....
    package: ntp ntpdate samba krb5-config krb5-locales krb5-user sssd
    wizard:
      kerberos:
        version5realm: EHE.EXECHEALTHGROUP.COM
        serversforrealm: 192.168.0.206 192.168.0.200
        adminstrative_server: 192.168.0.206
  ntp:
    path: /etc/ntp.conf
    replace:
      # Delete all pool entries and replace with lines below
      pool 192.168.0.206 #ehenydc01.ehe.exechealthgroup.com
      pool 192.168.0.200 #caldc03.ehe.exechealthgroup.com
    restart: True
    # sudo service ntp restart
  hosts-file:
    path: /etc/hosts
    servers: bastion ehenydc01 caldc03
    # see hosts example in ./notes
  netplan:
    path: /etc/netplan/50-cloud-init.yaml
    values:
            set-name: eth0
            nameservers:
              search: [ehe.exechealthgroup.com, ec2.internal]
              addresses: [192.168.0.206, 192.168.0.200, 127.0.0.53]
            # example ./etc_netplan_50-cloud-init.yaml
    cmd: netplan apply
  kerberos:
    conf_file:
      path: /etc/krb5.conf
        truncate: sudo truncate -s0 /etc/krb5.conf
        replace contents: #see the example I dropped in ./notes/krb5.conf
    createticket: kinit join
      password: [ehe_join]
      # prompts for password. Enter password
    listticket: klist
  samba:
    # see ./notes/etc_samba_smb.conf
    username map: /usr/local/samba/etc/user.map
        contents: !root = EHE\join
        cmd: mkdir -p /usr/local/samba/etc && touch /usr/local/samba/etc/user.map && echo -e '!root = EHE\join' > /usr/local/samba/etc/user.map
  winbind:
    # update nsswitch.conf append "winbind" to passwd and group fields
    append:
      passwd:         compat systemd winbind
      group:          compat systemd winbind
  pam-auth-update:
    profiles_enable: create home directory on login
      path: /etc/pam.d/common-session
        append: session	optional			pam_mkhomedir.so
  ssh:
    change: #PasswordAuthentication no
    restart: true
  join-active-directory:
    command: net ads join -k
  restart:
    services: smbd nmbd winbind ssh
    # systemctl restart smbd nmbd winbind ssh
  sudoers:
    command:

## EXPERIMENTAL BELOW HERE
  \*

  pam.d:
    path: /etc/pam.d/sshd
    change:
      # Standard Un*x authorization.
      # @include common-account
    add:
      account sufficient pam_succeed_if.so user ingroup [EHE\CODA Dev Users]
      account sufficient pam_succeed_if.so user ingroup [EHE\CODA Dev Admins]
      account sufficient pam_succeed_if.so user ingroup root

    */

- resources:
  - https://www.starwindsoftware.com/blog/ubuntu-join-a-server-to-an-active-directory-domain
  - https://wiki.samba.org/index.php/Setting_up_Samba_as_a_Domain_Member
  - https://wiki.samba.org/index.php/Setting_up_Samba_as_a_Domain_Member
  - https://www.suse.com/support/kb/doc/?id=7011689
  - https://www.systutorials.com/docs/linux/man/8-resolvconf/
  - https://wiki.archlinux.org/index.php/Active_Directory_Integration
  - https://www.linuxquestions.org/questions/linux-security-4/pam_succeed_if-so-help-needed-for-multiple-groups-648140/
  - https://likegeeks.com/linux-pam-easy-guide/
  - http://discreet-its.co.uk/2018/07/19/creating-etc-hosts-using-ansible/
  - https://netplan.io/reference
