---
- name: Upgrade all packages to the latest version
  become_user: root
  apt:
    name: "*"
    state: latest
    update_cache: yes
    autoremove: yes
    force_apt_get: True

- name: Install all required core packages
  become_user: root
  vars:
    newpackages:
      - ntp
      - ntpdate
      - winbind
      - samba
      - libnss-winbind
      - libpam-winbind
      - krb5-config
      - krb5-locales
      - krb5-user
  apt:
    name: "{{ newpackages }}"

- name: Install kops deployment tools with snap
  become_user: root
  vars:
    kopsnaps:
      - kubectl
      - helm
  shell: snap install "{{ item }}" --classic
  loop: "{{ kopsnaps }}"
  when:
    - kops_deploy is defined
