---
- name: Upgrade all packages to the latest version
  become_user: root
  apt:
    name: "*"
    state: latest
    update_cache: yes
    autoremove: yes
    force_apt_get: True

- name: Install all required packages
  become_user: root
  vars:
    newpackages:
      - ntp
      - ntpdate
      - winbind
      - samba
      - libnss-winbind
      - libpam-winbind
      - krb5-config
      - krb5-locales
      - krb5-user
  apt:
    name: "{{ newpackages }}"
