# License Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0.html).
---
- name: Install all required packages
  become_user: root
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      "{{ newpackages }}"
